# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'POT' do
  use_frameworks!

  # Pods for POT
  pod 'OAuthSwift'

  # Dependency Injection
  pod 'Swinject'
  pod 'SwinjectPropertyLoader'

  # Flair
  pod 'lottie-ios'

  target 'POTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'POTUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
